apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: peakees-app-metrics
  namespace: peakees-production
  labels:
    app: peakees
    component: monitoring
spec:
  selector:
    matchLabels:
      app: peakees
      component: app
  endpoints:
  - port: http
    path: /api/metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - peakees-production