apiVersion: v1
kind: Service
metadata:
  name: vntg-app-service
  namespace: vntg-production
  labels:
    app: vntg
    component: app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: vntg
    component: app
---
apiVersion: v1
kind: Service
metadata:
  name: vntg-headless
  namespace: vntg-production
  labels:
    app: vntg
    component: app
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: vntg
    component: app