name: API-Stub Validation

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
  schedule:
    # Run daily at 2 AM UTC to catch API drift
    - cron: '0 2 * * *'

jobs:
  validate-stubs:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate stub data schemas
      run: npm run validate:stubs
      
    - name: Run TypeScript compilation
      run: npm run type-check
      
    - name: Run linting
      run: npm run lint

  api-consistency-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[validate-api]')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup environment for real API testing
      run: |
        echo "NEXT_PUBLIC_USE_STUBS=false" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.local
        echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" >> .env.local
      
    - name: Start Next.js server
      run: |
        npm run build
        npm start &
        sleep 10
        
    - name: Run API-Stub sync validation
      run: npm run sync:api-stubs
      continue-on-error: true
      
    - name: Upload validation results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: api-validation-results
        path: |
          lib/stubs/stub-updates-*.json
          lib/stubs/validation-report-*.md
        retention-days: 30
        
    - name: Comment on PR if validation fails
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## ⚠️ API-Stub Validation Failed
            
            The API endpoints and stub data are out of sync. This means:
            
            - Real API responses don't match stub responses
            - E2E tests might pass locally but fail in production
            - Data structures may have changed
            
            ### Action Required
            1. Review the validation artifacts in this workflow
            2. Run \`npm run sync:api-stubs\` locally to see detailed differences
            3. Update stub data in \`lib/stubs/mock-data.ts\` to match real API
            4. Consider if API schema changes require TypeScript type updates
            
            ### Auto-fix Option
            If the API changes are intentional, you can:
            1. Run \`npm run sync:api-stubs\` locally
            2. Review and commit the generated stub updates
            3. Push the changes to update this PR
            `
          })

  e2e-stub-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Setup stub environment
      run: echo "NEXT_PUBLIC_USE_STUBS=true" >> .env.local
      
    - name: Build and start application
      run: |
        npm run build
        npm start &
        sleep 10
        
    - name: Run E2E tests with stubs
      run: npm run test:e2e:stubs
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-stub-test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7